### ISSUE TITLE
Is this repo alive?

### ISSUE THREAD

**Issue by egormalyutin** [luafun/luafun#50]

**Comment by tst2005** [comment]
Hello,

I don't know if this repo is still alive.
If you need functionnal programming in lua, you can take a look on https://github.com/Yonaba/Moses/

Regards,

**Comment by stuta** [comment]
Fuafun is grazy fast, Moses is not. See https://github.com/Yonaba/Moses/issues/58.

If someone could make Moses as fast as Luafun then I would use it.

**Comment by scrumit** [comment]
Does it matter that this repo is dormant, the code still works, as @stuta knows.

I think it may be some of the packaging that needs tidying up. I'll have a look and see if I can verify the comparison code:

````
local _ = require "moses" -- https://github.com/Yonaba/Moses/blob/master/doc/tutorial.md
local fn = require "luafun" -- https://github.com/rtsisyk/luafun
local function filterFn(x)
  return x % 2 == 0
end
local function mapFn(x)
  return x + 0.1
end
local function filterFn2(_, x)
  return x % 2 == 0
end
local function mapFn2(_, x)
  return x + 0.1
end
local time1 = os.clock()
local gen1 = fn.iter(arr):filter(filterFn):map(mapFn):take(3):totable()
time1 = os.clock() - time1
print(string.format('%.6f seconds: %s', time1, table.concat(gen1, ', ')))
local time2 = os.clock()
local gen2 = _(arr):filter(filterFn2):map(mapFn2):take(3):value()
time2 = os.clock() - time2
print(string.format('%.6f seconds: %s', time2, table.concat(gen2, ', ')))
print(string.format("time1: %.6f / time2: %.6f, luafun is %.0f times faster than moses", time1, time2, time2/time1))
````

**Comment by Totktonada** [comment]
I have agreement with @rtsisyk that Tarantool team may contribute to this repository after thorough peer review (as we do for tarantool itself).

Not much time for this activity, though...

**Comment by scrumit** [comment]
fantastic, can we fix the failing build flag, please? 

The log shows that packpack failed. Nearly all the pull requests since have passed, so it's more a case of making a change (or accepting a PR) and we should have the build flag changed.

I'll start using it, because it's tinier than other functional libraries.

**Comment by Totktonada** [comment]
To be honest, I don't get the problem regarding a build flag. Can you clarify (preferably in its own issue)?

**Comment by scrumit** [comment]
The status in the readme says the build is failing.

**Comment by kyukhin** [comment]
I guess this is not an issue.
