### ISSUE TITLE
Rock fails to install

### ISSUE THREAD

**Issue by DarkWiiPlayer** [luafun/luafun#66]
So apparently github blocks `git://` now, which causes installation to fail as the rockspec on luarocks.org hasn't yet been updated to use `git+https://` instead. Simply uploading a new version of the rockspec that uses HTTPS should easily fix this problem.

**Comment by ligurio** [comment]
We have already updated protocol in a [rockspec](https://github.com/luafun/luafun/blob/f126f9cc1ceedeff83eb8ca3f4df8e4f4cc96e85/fun-scm-1.rockspec#L4-L6):
```lua
source = {
    url = "git+https://github.com/luafun/luafun.git",
}
```

But our updated rockspec is not on [Luarocks server](https://luarocks.org/modules/rtsisyk/fun).

**Comment by DarkWiiPlayer** [comment]
Yes, I already saw that 😆

Is it possible that someone just quickly pushes the new version to luarocks.org though?

This may be trivial to fix with a bit of luarocks knowledge, but that doesn't apply to all (or even most) users, and it never looks good when installation fails because some dependency couldn't be fetched.

**Comment by Totktonada** [comment]
Luarocks 3.8.0 autoreplaces it: https://github.com/luarocks/luarocks/commit/9ff512e35455939f02eaec2318e3acc77782fdeb.

Anyway, I wrote to Roman T. to update the rockspec.

**Comment by ligurio** [comment]
@DarkWiiPlayer Use direct link to rockspec as a workaround:
`luarocks install https://raw.githubusercontent.com/luafun/luafun/master/fun-scm-1.rockspec --local`

**Comment by DarkWiiPlayer** [comment]
My problem isn't with installing the rock for myself (just downloaded the rockspec and changed the URL myself), but that it breaks `luarocks install` for any rocks that depend on it.

**Comment by rtsisyk** [comment]
Sorry for the late answer - updated.

**Comment by Totktonada** [comment]
@rtsisyk Updated the rockspec.
