### ISSUE TITLE
question about iterators

### ISSUE THREAD

**Issue by mvolkmann** [luafun/luafun#74]
I want to learn how to use a `for` loop to loop over the values in an iterator.
Why doesn't the `for` loop below work?
The error I get is "attempt to index a nil value"

```lua
fun = require("fun")
scores = {7, 4, 13}
function double(n) return n * 2 end
iter = fun.map(double, scores)
for v in iter() do
  print(v)
end
```

**Comment by Totktonada** [comment]
`<luafun iterator>:unwrap()` returns the usual `gen, param, state` triplet and it is suitable to place into a for loop.

**Comment by mvolkmann** [comment]
Thanks! I see that `for v in iter:unwrap() do` works.
